#!/bin/bash

set -e

ROOT_DIR=/usr/src/app
WORK_DIR=/workdir
INPUT_PATH=$1
OUTPUT_PATH=${2:-${WORK_DIR}/output.pdf}

if [[ -z $INPUT_PATH ]]; then
  echo "==> specify input. aborting"
  exit 1
fi
echo "==> in:  ${INPUT_PATH}"
echo "==> out: ${OUTPUT_PATH}"

if [[ $INPUT_PATH == s3://* ]]; then
  aws s3 cp ${INPUT_PATH} /tmp/input.pdf
  INPUT_PATH=/tmp/input.pdf
fi

# echo "=> Removing PDF annotations"
# pdf2ps -level3 $INPUT_PATH ${ROOT_DIR}/postscript.ps
# ps2pdf ${ROOT_DIR}/postscript.ps ${ROOT_DIR}/purified.pdf

echo "==> Generating PDF compliant with PDF/X-1a:2001"
PDFX_DEF_PATH=$ROOT_DIR/assets/PDFX_def.ps
ICC_PROFILE_PATH=$ROOT_DIR/assets/JapanColor2001Coated.icc
echo "==> PDFX_def.ps = ${PDFX_DEF_PATH}"
echo "==> ICC = ${ICC_PROFILE_PATH}"
gs \
  -dPDFX \
  -dBATCH \
  -dNOPAUSE \
  -dNOOUTERSAVE \
  -dPDFSTOPONERROR \
  -sDEVICE=pdfwrite \
  -dShowAnnots=false \
  -dNoOutputFonts \
  -dPDFSETTINGS=/prepress \
  -dUseCropBox \
  -dUseTrimBox \
  -dUseBleedBox \
  -dPrinted \
  -sProcessColorModel=DeviceCMYK \
  -sColorConversionStrategy=CMYK \
  -sColorConversionStrategyForImages=CMYK \
  -sOutputICCProfile=${ICC_PROFILE_PATH} \
  -sOutputFile="/tmp/output.pdf" ${PDFX_DEF_PATH} $INPUT_PATH

if [[ $OUTPUT_PATH == s3://* ]]; then
  aws s3 cp /tmp/output.pdf ${OUTPUT_PATH}
else
  cp /tmp/output.pdf ${OUTPUT_PATH}
fi