#!/bin/bash

set -e
shopt -s expand_aliases

ROOT_DIR=/usr/src/app
WORK_DIR=/workdir
INPUT_PATH=$1
OUTPUT_PATH=$2

if [[ -z $INPUT_PATH ]] || [[ -z $OUTPUT_PATH ]]; then
  echo "==> specify both input and output. aborting"
  exit 1
fi
echo "==> IN:  ${INPUT_PATH}"
echo "==> OUT: ${OUTPUT_PATH}"

# check AWS S3 resource uri
if [[ $INPUT_PATH == s3://* ]]; then
  if [[ -z $AWS_ACCESS_KEY_ID ]] || [[ -z $AWS_SECRET_ACCESS_KEY ]]; then
    echo "==> specify both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. aborting"
    exit 1
  fi
  echo "==> AWS S3 module enabled"

  alias cp="aws s3 cp"
fi

# copy source file to working directory
echo "==> Downloading artifact from '${INPUT_PATH}'"
cp ${INPUT_PATH} /tmp/input.pdf

echo "==> Font Summary [input]"
pdffonts /tmp/input.pdf

# echo "==> Removing PDF annotations"
# pdf2ps -level3 $INPUT_PATH ${ROOT_DIR}/postscript.ps
# ps2pdf ${ROOT_DIR}/postscript.ps ${ROOT_DIR}/purified.pdf

PDFX_DEF_PATH=$ROOT_DIR/assets/PDFX_def.ps
ICC_PROFILE_PATH=$ROOT_DIR/assets/JapanColor2001Coated.icc

echo "==> Making PDF compliant with PDF/X-1a:2001"
echo "> PDFX_def.ps = ${PDFX_DEF_PATH}"
echo "> ICC = ${ICC_PROFILE_PATH}"
echo "> INPUT = /tmp/input.pdf"

# -dUseCropBox \
# -dUseTrimBox \
# -dUseBleedBox \
gs \
  -dPDFX \
  -dBATCH \
  -dNOPAUSE \
  -dNOOUTERSAVE \
  -dPDFSTOPONERROR \
  -sDEVICE=pdfwrite \
  -dShowAnnots=false \
  -dNoOutputFonts \
  -dPDFSETTINGS=/prepress \
  -dPrinted \
  -sProcessColorModel=DeviceCMYK \
  -sColorConversionStrategy=CMYK \
  -sColorConversionStrategyForImages=CMYK \
  -sOutputICCProfile=${ICC_PROFILE_PATH} \
  -sOutputFile=/tmp/output.pdf \
  ${PDFX_DEF_PATH} \
  /tmp/input.pdf

echo "==> Font Summary [output]"
pdffonts /tmp/output.pdf

# save processed file
echo "==> Uploading artifact to '${OUTPUT_PATH}'"
cp /tmp/output.pdf ${OUTPUT_PATH}
